serial:
  dxl_port: "/dev/tty.usbserial-FTAO9VZP"
  pico_port: "/dev/tty.usbmodemF412FA77615C2"
  motor_driver_type: "r4"  # "pico" or "r4"

dynamixel:
  ids: [1, 2, 3]
  baud_rate: 57600
  model: "XM430"
  current_limit_ma: 500  # トルク制限 (mA)

control:
  loop_rate_hz: 20
